// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mnpxilgzzylodkneycpr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ucHhpbGd6enlsb2RrbmV5Y3ByIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxMjcwOTQsImV4cCI6MjA2ODcwMzA5NH0.v6Oy88tb9TG7zNcf0WuNjuQUyHQGu91D0RTH2NzUsZE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});